server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.1:3306/app
    username: root
    password: password
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
