openapi: 3.0.0
info:
  title: A minimal OpenAPI document
  version: 0.0.1

paths:
  /post:
    get:
      tags:
        - post-client
      operationId: getAllPosts
      responses:
        '200':
          content:
            application/json:
             schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
          description: posts returned successfully



components:
  schemas:
    Post:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string